version: '3.9'

services:
 db:
  container_name: diplom_db
  image: postgres:alpine
  restart: unless-stopped
  ports:
   - 8080:5432
  volumes:
   - ./logs:/var/log
  environment:
   - POSTGRES_DB=diplom_db
   - POSTGRES_USER=diplom_user
   - POSTGRES_PASSWORD=diplom_user
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres -d pythonapp_db"]
   interval: 1m30s
   timeout: 30s
   retries: 5
   start_period: 30s